name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
      with:
        path: server
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      
    - run: npm run build --if-present
    - run: npm test
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.4
      with: 
        key: ${(secrets.SSH_SECRET)}
        host: ${(SSH_HOST)}
        username: ${(secrets.SSH_USERNAME)}
        script: |
          pm2 delete scratchpay
          cd scratchpay
          git pull
          npm install
          npm build
          pm2 start dist/index.js --name "scratchpay"